### ISSUE TITLE
[🙏] Use Repository Instead of Project ID

### ISSUE THREAD

**Issue by ryanaross** [snyk-tech-services/backstage-plugin-snyk#97]
**Describe the user need**
We would like users to be able to use this plugin without manually gathering and maintaining a list of Snyk `project-id`. The Snyk Dashboard has a list of all projects underneath a repository, and in some cases (a monorepo for instance), this could be dozens of `project-id` which change frequently.

**Describe expected behaviour**
Ability for the Snyk plugin to list all the projects given just the org name and repo slug.

**Comment by aarlaud** [comment]
We're missing an endpoint to get the correlation repo<->projects currently. Investigating possible options in the meantime.

**Comment by IvanAlekseev** [comment]
@aarlaud do you have any updates? We are implementing backstage over 500 repos and it is not an easy job to fill in project ids

**Comment by emilkvarnhammar** [comment]
@aarlaud I agree, this is an important feature if the Backstage plugin should be useful in larger orgs. Filling in the project ids manually is not sustainable. Especially since other tools like snyk-api-import might add additional projects for the repo asynchronously. Any suggestion on how to handle that @aarlaud ? Can't you just use the remoteRepoUrl property supplied by the SNYK API to correlate betw. repo and projects?

**Comment by aarlaud** [comment]
I'll be closing this out. If any issue with the release, please open a new issue. Cheers !
